name: gekkoboot build

on: [push, pull_request]

jobs:
  build:
    name: Build gekkoboot
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential python3-pip p7zip-full
        pip3 install meson

    - name: Checkout gekkoboot
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch Qoob prebuilt
      run: curl -Lo res/ipl.rom https://github.com/redolution/gekkoboot/releases/download/r5.2/iplboot.gcb

    - name: Build gekkoboot
      run: |
        export PATH="$DEVKITPPC/bin:$PATH"
        meson setup . build --cross-file=devkitPPC.ini -Dfull_rom='enabled'
        meson compile -C build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gekkoboot
        path: build
