name: iplboot build

on: [push, pull_request]

jobs:
  build:
    name: Build iplboot
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3-pip p7zip-full
        pip3 install meson

    - name: Checkout iplboot
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Qoob prebuilt
      run: curl -Lo res/ipl.rom https://github.com/redolution/iplboot/releases/download/r5.2/iplboot.gcb

    - name: Build iplboot
      run: |
        export PATH="$DEVKITPPC/bin:$PATH"
        meson setup . build --cross-file=devkitPPC.ini
        ninja -C build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: iplboot
        path: build
